apiVersion: v1
kind: ConfigMap
metadata:
  name: packetbeat-deployment-config
data:
  packetbeat.yml: |-
    packetbeat.interfaces.device: any

    packetbeat.flows:
      timeout: 30s
      period: 10s

    processors:
      - add_cloud_metadata:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          in_cluster: true
          default_indexers.enabled: false
          default_matchers.enabled: false
          indexers:
            - pod_name:
          matchers:
            - field_format:
                format: 'default/%{[host.name]}'
      - add_host_metadata:
      - dns:
          type: reverse
          fields:
            source.ip: source.hostname
            destination.ip: destination.hostname
            
    packetbeat.protocols:
    - type: dns
      ports: [53]
      include_authorities: true
      include_additionals: true
    - type: http
      ports: [80, 8080, 8000, 5000, 8002]
    - type: mysql
      ports: [3306]
    - type: tls
      ports: [443]
    - type: icmp
      enabled: true
    
    packetbeat.procs.enabled: true

    cloud.id: ${ELASTIC_CLOUD_ID}
    cloud.auth: ${ELASTIC_CLOUD_AUTH}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: packetbeat
subjects:
- kind: ServiceAccount
  name: packetbeat
  namespace: default
roleRef:
  kind: ClusterRole
  name: packetbeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: packetbeat
rules:
- apiGroups: [""]
  resources:
  - nodes
  - namespaces
  - events
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  - deployments
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - nodes/stats
  verbs:
  - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: packetbeat
